spring:
  config:
    activate:
      on-profile: qa

build:
  version: 2.0

loans:
  message: Welcome to EzayBank Loans related QA APIs
  contactDetails:
    name: Ozn Klnc - Backend Developer
    email: ozn.klnc@example.com
  onCallSupport:
    - (666) 555-1234
    - (666) 555-5678