spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:loans
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
        - application_prod.yml
        - application_qa.yml
  profiles:
    active:
        - prod

server:
  port: 8090

build:
  version: 1.0

loans:
  message: Welcome to EzayBank Loans related local APIs
  contactDetails:
    name: John Doe - Backend Developer
    email: john.doe@example.com
  onCallSupport:
    - (555) 555-1234
    - (555) 555-5678